### ISSUE TITLE
API incorrectly rejects API keys and responds with the API key.

### ISSUE THREAD

**Issue by romainmenke** [cultuurnet/udb3-php#380]
This bug is intermittent and we have not found a pattern behind it.
The API key is correct as it works about half the time.

`{"title":"Invalid API key provided (<REDACTED>).","type":"about:blank","status":400}`

Aside from the rejections it is also a very bad practice to place the "secret" API key in the response body. (We replaced it with `<REDACTED>`)

At least replace a large part of the key with `xxxxxx`

**Comment by Stiksels** [comment]
hi @romainmenke , thanks for your feedback. This bug has already been reported and we are working on a fix at the moment (internal ref: III-2701). The cause is an unstable external service used to validate the apiKey.

When this bug is fixed, this error message should not occur anymore when using a valid key. I also noted your suggestion to edit the HTTP response and replace the printed apiKey with a truncated version and will take it up with the dev team.

**Comment by Stiksels** [comment]
@romainmenke sorry for the late update. The bug was fixed quite some time ago, but your suggestion remained open. We don't see a serious risk to print the full apiKey in the response, as the API is using SSL. So the traffic is already encrypted, and the apiKey is also included in the request headers or request URL. So if there was a way to sniff it, it could be sniffed from the headers / url anyway...

Hope this is a sufficient reply to your concerns

**Comment by romainmenke** [comment]
Hi,

I strongly disagree with your statement about printing the full apiKey in the response. 

Adding a private key to a header or request url is a manual action of which an implementer is aware. They can take steps to make sure this information does not leak to 3rd parties (e.g. log sinks)

Adding private information in responses when this behaviour is undocumented is not safe at all. This required implementers to scan any response from your api for secrets and strip these.

Please fix this!
